config/routes.rb
Magento::Application.routes.draw do

  resources :wishlists,:shallow=>true do
    resources :wishlist_items
  end

  resources :reviews
  match 'wishlists/:wishlist_id/add/:product_id'=>"wishlist_items#create",:as=>"wishlist_add"
  match 'populate/:class_name'=>"products#populate", :as=>"populate"
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end
  
  resources :authentications

  resources :products
  get "products/search"
  match "products/category/:category_id"=>"products#index",:as=>'category'

  root :to => 'products#index'

end

app/models/wishlist_item.rb
class WishlistItem < ActiveRecord::Base
  attr_accessible :product_id, :wishlist_id
  
  belongs_to :wishlist
  
  def product 
    Product.find(product_id)
  end
end

app/controllers/wishlist_items_controller.rb
class WishlistItemsController < ApplicationController
  def index
    @wishlist = Wishlist.find(params[:wishlist_id])
    @wishlist_items = @wishlist.wishlist_items
  end

  def show
    @wishlist_item = WishlistItem.find(params[:id])
  end

  def new
    @wishlist = Wishlist.find(params[:wishlist_id])
    @wishlist_item = @wishlist.wishlist_items.build
  end

  def create
    if !params[:product_id].nil?
      Wishlist.find(params[:wishlist_id]).wishlist_items.build(:product_id=>params[:product_id]).save
      redirect_to :back
    else
      @wishlist_item = WishlistItem.new(params[:wishlist_item])
      if @wishlist_item.save
        redirect_to @wishlist_item, :notice => "Successfully created wishlist item."
      else
        render :action => 'new'
      end
    end
  end

  def edit
    @wishlist_item = WishlistItem.find(params[:id])
  end

  def update
    @wishlist_item = WishlistItem.find(params[:id])
    if @wishlist_item.update_attributes(params[:wishlist_item])
      redirect_to @wishlist_item, :notice  => "Successfully updated wishlist item."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @wishlist_item = WishlistItem.find(params[:id])
    @wishlist_item.destroy
    redirect_to :back, :notice => "Successfully destroyed wishlist item."
  end
end

app/helpers/wishlist_items_helper.rb
module WishlistItemsHelper
end

app/views/wishlist_items/_form.html.haml
= form_for [@wishlist,@wishlist_item] do |f|
  = f.error_messages
  %p
    = f.label :product_id
    %br/
    = f.number_field :product_id
  %p
    = f.label :wishlist_id
    %br/
    = f.number_field :wishlist_id
  %p= f.submit

app/views/wishlist_items/_wishlist_item.html.haml
-product=wishlist_item.product
.row.moveDown
  .span2
    =image_tag product.thumbnail_url, :width=>80
  .span8
    %h4=link_to product.name, product_path(wishlist_item.product_id)
    .row
      .span2 Price: #{product.price}
      .span3 added #{time_ago_in_words(wishlist_item.created_at)} ago
      .span3=link_to 'remove from list', wishlist_item, :confirm => 'Are you sure?', :method => :delete, :class=>'btn danger' if wishlist_item.wishlist.user==current_user

app/views/wishlist_items/edit.html.haml
- title "Edit Wishlist Item"
= render 'form'
%p
  = link_to "Show", @wishlist_item
  |
  \#{link_to "View All", wishlist_items_path}

app/views/wishlist_items/index.html.haml
- title "Wishlist Items"
%table
  %tr
    %th Product
    %th Wishlist
  - for wishlist_item in @wishlist_items
    %tr
      %td= wishlist_item.product_id
      %td= wishlist_item.wishlist_id
      %td= link_to "Show", wishlist_item
      %td= link_to "Edit", edit_wishlist_item_path(wishlist_item)
      %td= link_to "Destroy", wishlist_item, :confirm => 'Are you sure?', :method => :delete
%p= link_to "New Wishlist Item", new_wishlist_wishlist_item_path(@wishlist)

app/views/wishlist_items/new.html.haml
- title "New WishlistItem"
= render 'form'
%p= link_to "Back to List", wishlist_wishlist_items_path(@wishlist)

app/views/wishlist_items/show.html.haml
- title "Wishlist Item"
%p
  %strong Product:
  = @wishlist_item.product_id
%p
  %strong Wishlist:
  = @wishlist_item.wishlist_id
%p
  = link_to "Edit", edit_wishlist_item_path(@wishlist_item)
  |
  \#{link_to "Destroy", @wishlist_item, :confirm => 'Are you sure?', :method => :delete} |
  \#{link_to "View All", wishlist_items_path}