config/routes.rb
Magento::Application.routes.draw do

  resources :wishlists,:shallow=>true do
    resources :wishlist_items
  end

  resources :reviews
  match 'wishlists/:wishlist_id/add/:product_id'=>"wishlist_items#create",:as=>"wishlist_add"
  match 'populate/:class_name'=>"products#populate", :as=>"populate"
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end
  
  resources :authentications

  resources :products
  get "products/search"
  match "products/category/:category_id"=>"products#index",:as=>'category'

  root :to => 'products#index'

end

app/models/wishlist.rb
class Wishlist < ActiveRecord::Base
  attr_accessible :name, :user_id
  
  belongs_to :user
  has_many :wishlist_items
  
  def products
    wishlist_items.map{|item| item.product} 
  end
  
  def find_item product
    wishlist_items.find_by_product_id(product.id)
  end
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  def index
    @wishlists = Wishlist.all
  end

  def show
    @wishlist = Wishlist.find(params[:id])
    @wishlist_items = @wishlist.wishlist_items
  end

  def new
    @wishlist = Wishlist.new
  end

  def create
    @wishlist = current_user.wishlists.build(params[:wishlist])
    if @wishlist.save
      redirect_to root_path, :notice => "Successfully created wishlist."
    else
      render :action => 'new'
    end
  end

  def edit
    @wishlist = Wishlist.find(params[:id])
  end

  def update
    @wishlist = Wishlist.find(params[:id])
    if @wishlist.update_attributes(params[:wishlist])
      redirect_to @wishlist, :notice  => "Successfully updated wishlist."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @wishlist = Wishlist.find(params[:id])
    @wishlist.destroy
    redirect_to root_path, :notice => "Successfully destroyed wishlist."
  end
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/wishlists/_form.html.haml
= form_for @wishlist do |f|
  = f.error_messages
  .row.moveDown
    = f.label :name, "Wishlist Name"
    .input
      = f.text_field :name

   
    .input.moveDown
      = f.submit :class=>'btn primary'

app/views/wishlists/_summary.html.haml
%h2 Wishlist
-if user_signed_in?
  -if current_user.wishlists.empty?
    =link_to "Create a wishlist",new_wishlist_path, :class=>'btn primary'
  -else
    %ul.unstyled
      -current_user.wishlists.each do |wishlist|
        %li=link_to "#{wishlist.name} ( #{wishlist.wishlist_items.count} )",wishlist
    =link_to "Add another wishlist",new_wishlist_path, :class=>'btn'
-else
  Please #{link_to 'sign in',user_omniauth_authorize_path(:facebook)} to access your wishlists.

app/views/wishlists/edit.html.haml
- title "Edit Wishlist"
= render 'form'
%p
  = link_to "Show", @wishlist
  |
  \#{link_to "View All", wishlists_path}

app/views/wishlists/index.html.haml
- title "Wishlists"
%table
  %tr
    %th Name
    %th(colspan=4) User
  - for wishlist in @wishlists
    %tr
      %td= wishlist.name
      %td= wishlist.user_id
      %td= link_to "Show", wishlist, :class=>'btn'
      %td= link_to "Edit", edit_wishlist_path(wishlist), :class=>'btn'
      %td= link_to "Destroy", wishlist, :confirm => 'Are you sure?', :method => :delete, :class=>'btn danger'
%p= link_to "New Wishlist", new_wishlist_path, :class=>'btn'

app/views/wishlists/new.html.haml
- title "New Wishlist"
= render 'form'
%p= link_to "Back to List", wishlists_path

app/views/wishlists/show.html.haml
%h3 Wishlist: #{@wishlist.name}
= link_to "rename wishlist", edit_wishlist_path(@wishlist), :class=>'btn small'
|
\#{link_to "delete wishlist", @wishlist, :confirm => 'Are you sure?', :method => :delete, :class=>'btn danger small'} 

-if @wishlist_items.empty?
  .alert-message.warning.moveDown
    %p This wishlist is currently empty! You should add something to it!
-else
  =render @wishlist_items
  