config/routes.rb
Magento::Application.routes.draw do

  resources :wishlists,:shallow=>true do
    resources :wishlist_items
  end

  resources :reviews
  match 'wishlists/:wishlist_id/add/:product_id'=>"wishlist_items#create",:as=>"wishlist_add"
  match 'populate/:class_name'=>"products#populate", :as=>"populate"
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end
  
  resources :authentications

  resources :products
  get "products/search"
  match "products/category/:category_id"=>"products#index",:as=>'category'

  root :to => 'products#index'

end

app/models/product.rb
class Product
  include ApplicationHelper
  include Mongoid::Document
  field :price, type: Float
  field :sku, type: String
  field :name, type: String
  field :image_url, type: String
  field :small_image_url, type: String
  field :thumbnail_url, type: String
  field :short_description, type: String
  field :long_description, type: String
  field :visibility, type: Integer
  has_and_belongs_to_many :categories
  scope :visible, where(:visibility.in=>[2,4])
  has_many :reviews
  
  def self.populate
    products = MagentoAPI.xmlcall('product.list')
    products.each do |product|
      puts product_id = product['product_id'].to_i
      category_ids = product['category_ids'].map{|x| x.to_i}
      
      product_info = MagentoAPI.call 'product.info',:string=>product_id
      image = MagentoAPI.call 'product_media.list',:string=>product_id
      image.each do |hash|
        name = hash['types'][:item]
        if name.is_a? Array
          name.each do |sub_name|
            instance_variable_set "@#{sub_name}_url", hash['url']  
          end 
        else
          instance_variable_set "@#{name}_url", hash['url']  
        end
      end
      x= Product.find_or_create_by(:id => product_id)
      x.update_attributes(
        :price => product_info['price'],
        :sku => product['sku'],
        :name => product['name'],
        :short_description => product_info['short_description'],
        :long_description => product_info['description'],
        :image_url => @image_url,
        :thumbnail_url => @thumbnail_url,
        :small_image_url => @small_image_url,
        :visibility=> product_info['visibility'].to_i,
        :category_ids => category_ids
      )  
      x.categories.map{|cat| cat.old_products << x}
    end
  end
  
  def pprice
    print_price(price)
  end
  
  def category
    categories[0]
  end
  
  def root_category
    categories[0].root_parent
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    
    if params[:category_id]
      @category = Category.find(params[:category_id].to_i)
      @products = @category.products
      @products = Kaminari.paginate_array(@products).page(params[:page]).per(4)
    else
      @products = Product.all.visible.page(params[:page]).per(4)
    end
  end
   
  def show
    @product = Product.find(params[:id].to_i)
    @review = Review.new
  end

  def search
  end
  
  def populate 
    eval(params[:class_name].capitalize).populate
    redirect_to :back
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_category-nav.html.haml
-if category["is_active"]=="1"
  %li=link_to category['name'],category_path(category['category_id']),:class=>"#{category["name"] == @category["name"] ? 'active' : ''}" 

-#  -unless category["children"].empty? 
-#    %ul= render :partial=>'products/category',:collection=>category["children"],:as=>:category 

app/views/products/_category-topbar.html.haml
.topbar
  .topbar-inner
    .container
      %h3= link_to 'Ruby Magento', 'root_path'
      %ul.nav= render :partial=>'products/category-nav',:collection=>category["children"],:as=>:category
      

app/views/products/_product.html.haml
.row.product
  .span2.prodImage
    =image_tag product.thumbnail_url, :width=>90
  .span6
    %h4=link_to product.name, product
    %p=raw product.short_description
  .span2.price

    %p= "Price: #{product.pprice}"
    -if user_signed_in? and !current_user.wishlists.empty?
      .add_to_wishlist
        %h5 Wishlist it!
        %ul.wishLists
          -current_user.wishlists.each do |wishlist|
            -if wishlist.products.include?(product)
              %li=link_to "#{wishlist.name}", wishlist_item_path(wishlist.find_item(product)),:method=>:delete, :class=>"remList", |
              :data=> {"original-title"=>"Remove #{product.name} from #{wishlist.name}"}
            -else
              %li=link_to "#{wishlist.name}", wishlist_add_path(wishlist.id,product.id),:class=>"addList", |
              :data=> {"original-title"=>"Add #{product.name} to #{wishlist.name}"}
            

app/views/products/index.html.haml
%h2=@category.nil? ? "All Products" : @category.name

=render :partial=>'products/product',:as=>:product,:collection=>@products
  
= paginate @products  

app/views/products/search.html.haml
<h1>Products#search</h1>
<p>Find me in app/views/products/search.html.erb</p>

app/views/products/show.html.haml
%h1=@product.name
.row
  .span4
    =image_tag @product.image_url,:width=>210,:class=>'mainImg'

    -# MULTIPLE SIZES IN HERE JUST TO SEE HOW THEY LOOK
    %ul.media-grid
      -# BIG ONES, ONLY TWO TO A LINE
      %li
        %a{:href=>'#'}
          %img{:src=>'http://placehold.it/90x90'}
      %li
        %a{:href=>'#'}
          %img{:src=>'http://placehold.it/90x90'}
      -# SMALLER ONES, FOUR TO A LINE
      %li
        %a{:href=>'#'}
          %img{:src=>'http://placehold.it/30x30'}
      %li
        %a{:href=>'#'}
          %img{:src=>'http://placehold.it/30x30'}
      %li
        %a{:href=>'#'}
          %img{:src=>'http://placehold.it/30x30'}
      %li
        %a{:href=>'#'}
          %img{:src=>'http://placehold.it/30x30'}



  .span6
    .row
      .span2
        -if @product.price.nil?  
          %h3 Price not available
        -else
          %h3=@product.pprice
      .span2
        =link_to 'Wishlist It!', '#', :class=>'btn'
      .span2
        =link_to 'Buy it!', '#', :class=>'btn primary'

    -# SIZE/VARIANT OPTIONS - PLACEHOLDER
    
    -#.row
    -if false
      %form.variations.row
        %label.span2{:for=>'variant'} Size
        -#.input
        .span4
          %select.span4{:name=>'variant', :id=>'variant'}
            %option S
            %option M
            %option L
            %option XL
            %option XXL

    -# DESCRIPTIONS / SPECS / REVIEWS TABS
    %ul.tabs
      %li{:class=>"#{params[:q]=='reviews' ? '' : 'active'}"}
        =link_to 'Description', '#desc'
      %li
        =link_to 'Specs', '#specs'
      %li{:class=>"#{params[:q]=='reviews' ? 'active' : ''}"}
        =link_to 'Reviews', '#reviews'
      
      
    .tab-content
      .tab-pane#desc{:class=>"#{params[:q]=='reviews' ? '' : 'active'}"}
        %p.full_desc=raw @product.long_description
        
      .tab-pane#specs
        %p Curabitur ut lobortis enim. Fusce accumsan faucibus faucibus. In bibendum ipsum non odio eleifend pulvinar. Mauris eget augue a erat hendrerit sodales. Nullam adipiscing lorem nec est fermentum iaculis. Nulla facilisi. Integer tempus lacus nec ligula lacinia in vestibulum sem fermentum. Aliquam erat enim, malesuada eu pulvinar a, fermentum vel turpis. Sed ultricies odio sit amet enim suscipit quis gravida dolor malesuada. Aenean at odio lectus.
      .tab-pane#reviews{:class=>"#{params[:q]=='reviews' ? 'active' : ''}"}
        .row.span5#review
          -if current_user
            =form_for @review do |f|
              =f.text_field :title,:placeholder=>"Title"
              =f.text_area :content,:rows=>4
              =f.hidden_field :user_id,:value=>current_user.id
              =f.hidden_field :product_id, :value=>@product.id
              =f.submit 'submit review',:class=>"btn"
          -else
            =link_to 'sign in to leave a review',user_omniauth_authorize_path(:facebook)  
          =render @product.reviews.reverse
      
  